name: context_example
on: push
env:
 my_action: ${{ github.action }}
 my_actor: ${{ github.actor }}
jobs:
 Env_context:
  name: context_test
  runs-on: ubuntu-latest
  steps:
      - name: print context env
        run: |
           echo "Print env values:"
           echo "Action! $my_action"
           echo "Actor! $my_actor"
        
    
