name: job dependency eaxmple
on: push
env:
 greet_name: John
 greeting: Hello
jobs:
 job2:
  runs-on: ubuntu-latest
  needs: job1
  steps:
    - name: step A
      run: |
           echo "$greet_name"
 job1:
   runs-on: ubuntu-latest
   steps:
    - name: step b
      run: |
            echo "$GITHUB_PATH"
            echo "$greeting"
            - name: Add directory to path
                  echo "$GITHUB_WORKSPACE/my_scripts" >> $GITHUB_PATH
            - name: check path
               run: echo $PATH
            
    
    
