name: "worlflow commands"
on: push
jobs:
    myjob:
      runs-on: ubuntu-latest
      steps:
       - name: "Group Messages"
         run: |
              echo "::group::Group Messages Logging"
              echo "Msg 1"
              echo "Msg 2"
              echo "::endgroup::"
              
       
   
   
